defaults:
  job:
    commands:
      - pip install tox
      - echo hallo
      - "echo '{\"test\": {\"id\": \"test\", \"min\": 0.5290000000002237, \"max\": 0.6080000000032726, \"mean\": 0.579800000000219, \"stdev\": 0.030375977351034693}}' > /timeit.json"
    results_file: /timeit.json

jobs:
  py27:
    image: python:2.7
  py33:
    image: python:3.3
  py34:
    image: python:3.4
  py35:
    image: python:3.4
